paper:
	pdflatex main.tex
	bibtex main
	pdflatex main.tex
	pdflatex main.tex
	open main.pdf

clean:
	rm *.aux
	rm *.bbl
	rm *.blg
	rm *.log
	rm *.out

quick:
	pdflatex main.tex
	open main.pdf

response1:
	pdflatex response1.tex
	pdflatex response1.tex
	open response1.pdf
